# BASE DE DONN\u00c9ES
spring.datasource.url=jdbc:postgresql://localhost:5432/traveldb
spring.datasource.username=postgres
spring.datasource.password=jocelyn2812

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# THYMELEAF
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# SERVEUR \u2014 Port chang\u00e9 !
server.port=8009

# APP
spring.application.name=TravelApp