# =========================
# BASE DE DONNEES POSTGRESQL
# =========================

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# =========================
# JPA / HIBERNATE
# =========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# THYMELEAF
# =========================

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# =========================
# APPLICATION
# =========================

spring.application.name=TravelApp

# Port dynamique Railway
server.port=${PORT:8080}

# =========================
# SPRING
# =========================

spring.main.allow-circular-references=true

# =========================
# LOGS
# =========================

logging.level.com.travelapp=DEBUG
logging.level.org.springframework.security=INFO